#!/bin/sh

# Source functions-xes.sh
. `dirname $0`/functions-xes.sh 2> /dev/null ||
. `which functions-xes.sh` 2> /dev/null

# Try to detect board name
BOARD=`xes_board_name 2> /dev/null`
# Default sensors location in sysfs
SYS_HWMON=/sys/class/hwmon

printf "Temperature sensor readings"
[ -z "$BOARD" ] && printf ":\n\n" || printf " for $BOARD:\n\n"
for sensdir in `ls -1 $SYS_HWMON`; do
    if [ -e $SYS_HWMON/$sensdir/name ]; then
        sensor="$SYS_HWMON/$sensdir"
    else
        sensor="$SYS_HWMON/$sensdir/device"
    fi
    [ -d $sensor ] || continue
    for input in `ls -1 $sensor/*_input`; do
        label=`echo $input | sed 's/input/label/'`
        if [ -e $label ]; then
            name=`cat $sensor/name`.`cat $label`
        else
            name=`cat $sensor/name`.`basename $input`
        fi
        temp=$(((`cat $input` + 500) / 1000))
        echo "$name: $temp C"
    done
done
