#!/bin/sh

EDAC_DIR=/sys/devices/system/edac

if [ ! -d $EDAC_DIR ]; then
    echo "EDAC not supported on this system"
    exit 1
fi

FILES=`find $EDAC_DIR -maxdepth 3 -name 'ce*_count' -o -name 'ue*_count'`

if [ -z "$FILES" ]; then
    echo "EDAC enabled, but no driver found with support for error counters"
    exit 1
fi

for x in $FILES; do
    echo "$x: `cat $x`" | sed "s#${EDAC_DIR}/[^/]*/##g"
done

